language: node_js
node_js:
- '10'
branches:
  only:
  - source
before_install:
# - openssl aes-256-cbc -K $encrypted_c4acb3b301e0_key -iv $encrypted_c4acb3b301e0_iv
  # -in .travis/id_rsa_blog.enc -out .travis/id_rsa_blog -d
- openssl aes-256-cbc -K $encrypted_c4acb3b301e0_key -iv $encrypted_c4acb3b301e0_iv 
  -in .travis/id_rsa_blog.enc -out ~/.ssh/id_rsa -d

- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Observer-jin"
- git config --global user.email guichongsui@163.com
install:
- npm install
script:
- hexo clean && hexo g -d
